require 'docx/containers'
require 'docx/elements'
require 'docx/errors'
require 'docx/helpers'
require 'nokogiri'
require 'stringio'
require 'zip'

module Docx
  # The Document class wraps around a docx file and provides methods to
  # interface with it.
  #
  #   # get a Docx::Document for a docx file in the local directory
  #   doc = Docx::Document.open("test.docx")
  #
  #   # get the text from the document
  #   puts doc.text
  #
  #   # do the same thing in a block
  #   Docx::Document.open("test.docx") do |d|
  #     puts d.text
  #   end
  class Document
    include Docx::SimpleInspect
    
    # A path with * indicates that there are possibly multiple documents
    # matching that glob, eg. word/header1.xml, word/header2.xml
    DOCUMENT_PATHS = {
      headers: "word/header*.xml",
      footers: "word/footer*.xml",
      numbering: "word/numbering.xml"
    }
    IMAGE_FIT_MODES = %i[cover contain stretch].freeze
    CM_TO_EMU = 360_000
    MAX_IMAGE_WIDTH_EMU = 5_486_400
    CONTENT_TYPES_NS = 'http://schemas.openxmlformats.org/package/2006/content-types'
    CONTENT_TYPES_PATH = '[Content_Types].xml'
    CONTENT_TYPE_MAPPINGS = {
      'png' => 'image/png',
      'jpg' => 'image/jpeg',
      'jpeg' => 'image/jpeg',
      'gif' => 'image/gif',
      'bmp' => 'image/bmp',
      'emf' => 'image/x-emf',
      'wmf' => 'image/x-wmf',
      'tiff' => 'image/tiff',
      'tif' => 'image/tiff'
    }.freeze
    NUMBERING_CONTENT_TYPE = 'application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml'
    NUMBERING_REL_TYPE = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering'
    XML_NAMESPACES = {
      'w' => 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
      'a' => 'http://schemas.openxmlformats.org/drawingml/2006/main',
      'r' => 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
      'wp' => 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing',
      'pic' => 'http://schemas.openxmlformats.org/drawingml/2006/picture'
    }.freeze

    attr_reader :xml, :doc, :zip, :styles, :headers, :footers, :numbering

    def initialize(path_or_io, options = {})
      @replace = {}

      # if path-or_io is string && does not contain a null byte
      if (path_or_io.instance_of?(String) && !/\u0000/.match?(path_or_io))
        @zip = Zip::File.open(path_or_io)
      else
        @zip = Zip::File.open_buffer(path_or_io)
      end

      document = @zip.glob('word/document*.xml').first
      raise Errno::ENOENT if document.nil?

      @document_xml = document.get_input_stream.read
      @doc = Nokogiri::XML(@document_xml)
      load_styles
      extract_documents
      yield(self) if block_given?
    ensure
      @zip.close unless @zip.nil?
    end

    # This stores the current global document properties, for now
    def document_properties
      {
        font_size: font_size,
        hyperlinks: hyperlinks
      }
    end

    # With no associated block, Docx::Document.open is a synonym for Docx::Document.new. If the optional code block is given, it will be passed the opened +docx+ file as an argument and the Docx::Document oject will automatically be closed when the block terminates. The values of the block will be returned from Docx::Document.open.
    # call-seq:
    #   open(filepath) => file
    #   open(filepath) {|file| block } => obj
    def self.open(path, &block)
      new(path, &block)
    end

    def paragraphs
      @doc.xpath('//w:document//w:body/w:p').map { |p_node| parse_paragraph_from p_node }
    end

    def bookmarks
      bkmrks_hsh = {}
      bkmrks_ary = @doc.xpath('//w:bookmarkStart').map { |b_node| parse_bookmark_from b_node }
      bkmrks_ary += @headers.values.map { |xml_doc| xml_doc.xpath('//w:bookmarkStart').map { |b_node| parse_bookmark_from b_node } }.flatten
      bkmrks_ary += @footers.values.map { |xml_doc| xml_doc.xpath('//w:bookmarkStart').map { |b_node| parse_bookmark_from b_node } }.flatten
      # auto-generated by office 2010
      bkmrks_ary.reject! { |b| b.name == '_GoBack' }
      bkmrks_ary.each { |b| bkmrks_hsh[b.name] = b }
      bkmrks_hsh
    end

    def to_xml
      Nokogiri::XML(@document_xml)
    end

    def tables
      @doc.xpath('//w:document//w:body//w:tbl').map { |t_node| parse_table_from t_node }
    end

    # Some documents have this set, others don't.
    # Values are returned as half-points, so to get points, that's why it's divided by 2.
    def font_size
      size_value = @styles&.at_xpath('//w:docDefaults//w:rPrDefault//w:rPr//w:sz/@w:val')&.value

      return nil unless size_value

      size_value.to_i / 2
    end

    # Hyperlink targets are extracted from the document.xml.rels file
    def hyperlinks
      hyperlink_relationships.each_with_object({}) do |rel, hash|
        hash[rel.attributes['Id'].value] = rel.attributes['Target'].value
      end
    end

    def hyperlink_relationships
      @rels.xpath("//xmlns:Relationship[contains(@Type,'hyperlink')]")
    end

    # Image targets are extracted from the document.xml.rels file.
    # Returned as { "rIdX" => "word/media/imageX.png" }.
    def images
      image_relationships.each_with_object({}) do |rel, hash|
        hash[rel.attributes['Id'].value] = normalize_entry_path(rel.attributes['Target'].value)
      end
    end

    def image_relationships
      @rels.xpath("//xmlns:Relationship[contains(@Type,'/image')]")
    end

    ##
    # *Deprecated*
    #
    # Iterates over paragraphs within document
    # call-seq:
    #   each_paragraph => Enumerator
    def each_paragraph
      paragraphs.each { |p| yield(p) }
    end

    # call-seq:
    #   to_s -> string
    def to_s
      paragraphs.map(&:to_s).join("\n")
    end

    # Output entire document as a String HTML fragment
    def to_html
      paragraphs.map(&:to_html).join("\n")
    end

    # Substitute a placeholder across runs in every paragraph of the document,
    # including paragraphs nested inside table cells. Delegates to
    # Paragraph#substitute so placeholders split across multiple runs are matched.
    #
    #   match: String | Regexp
    #   multiline: when true, "\n" in replacement becomes a soft line break (<w:br/>)
    def substitute_across_runs(match, replacement, multiline: false)
      @doc.xpath('//w:p', XML_NAMESPACES).each do |p_node|
        Elements::Containers::Paragraph.new(p_node, document_properties, self)
                                       .substitute(match, replacement, multiline: multiline)
      end
      self
    end

    # Remove unfilled placeholder text matching +pattern+ from every paragraph,
    # including paragraphs inside table cells. Uses Paragraph#substitute for
    # cross-run safety. Idempotent; returns self.
    def strip_unfilled_placeholders(pattern: /\{\{.*?\}\}/)
      @doc.xpath('//w:p', XML_NAMESPACES).each do |p_node|
        Elements::Containers::Paragraph.new(p_node, document_properties, self)
                                       .substitute(pattern, '')
      end
      self
    end

    # High-level template render entry. Keys are placeholder names; value types
    # determine handling. Returns self for chaining.
    #
    # Processing order: text → tables → images → checkboxes → content_controls
    # → strip_unfilled (when enabled).
    def render(text: {}, images: {}, checkboxes: {}, content_controls: {}, tables: [],
               multiline: true, strip_unfilled: false, strict: false, image_options: {})
      text.each do |placeholder, value|
        substitute_across_runs(placeholder, value.to_s, multiline: multiline)
      end

      tables.each do |table_spec|
        render_table_rows(table_spec, multiline: multiline, strict: strict)
      end

      images.each do |placeholder, source|
        render_image(placeholder, source, image_options: image_options, strict: strict)
      end

      checkboxes.each do |locator, checked|
        with_strict_rescue(strict) { set_checkbox(locator, checked: checked) }
      end

      content_controls.each do |tag_or_alias, checked|
        with_strict_rescue(strict) { check_content_control(tag_or_alias, checked: checked) }
      end

      strip_unfilled_placeholders if strip_unfilled

      self
    end

    # Save document to provided path
    # call-seq:
    #   save(filepath) => void
    def save(path)
      update
      Zip::OutputStream.open(path) do |out|
        written_entries = {}
        zip.each do |entry|
          next unless entry.file?

          out.put_next_entry(entry.name)
          value = @replace[entry.name] || zip.read(entry.name)
          written_entries[entry.name] = true

          out.write(value)
        end

        @replace.each do |entry_name, contents|
          next if written_entries[entry_name]

          out.put_next_entry(entry_name)
          out.write(contents)
        end
      end
      zip.close
    end

    # Output entire document as a StringIO object
    def stream
      update
      stream = Zip::OutputStream.write_buffer do |out|
        written_entries = {}
        zip.each do |entry|
          next unless entry.file?

          out.put_next_entry(entry.name)
          written_entries[entry.name] = true

          if @replace[entry.name]
            out.write(@replace[entry.name])
          else
            out.write(zip.read(entry.name))
          end
        end

        @replace.each do |entry_name, contents|
          next if written_entries[entry_name]

          out.put_next_entry(entry_name)
          out.write(contents)
        end
      end

      stream.rewind
      stream
    end

    alias text to_s

    def replace_entry(entry_path, file_contents)
      @replace[entry_path] = file_contents
    end

    # Replace an image by relationship ID (e.g. "rId5") or by archive entry path
    # (e.g. "word/media/image1.png").
    #
    # replacement_source accepts an IO-like object (responds to #read) or a file path.
    def replace_image(image_reference, replacement_source)
      image_entry_path = resolve_image_entry_path(image_reference)
      replace_entry(image_entry_path, read_replacement_source(replacement_source))
    end

    # Replace an existing image located by placeholder text in any paragraph.
    #
    # The search host is the paragraph containing the placeholder, or its table cell
    # ancestor when the paragraph lives inside a cell (image may be in another paragraph
    # within the same cell).
    #
    # Options:
    #   fit: :cover | :contain | :stretch (default: :stretch)
    #   cleanup_placeholder: true | false (default: true)
    #   width: width in cm
    #   height: height in cm
    def replace_image_by_placeholder(placeholder, replacement_source, options = {})
      paragraph = find_paragraph_by_placeholder(placeholder)
      raise Errors::ImagePlaceholderNotFound, "Placeholder not found: #{placeholder}" if paragraph.nil?

      host = paragraph.at_xpath('./ancestor::w:tc[1]', XML_NAMESPACES) || paragraph
      cleanup_kind = host.name == 'tc' ? :cell : :paragraph
      image_not_found_message = if cleanup_kind == :cell
                                  "No image found in the same cell as placeholder: #{placeholder}"
                                else
                                  "No image found in the same paragraph as placeholder: #{placeholder}"
                                end

      replace_image_within_host(
        host,
        placeholder,
        replacement_source,
        options,
        cleanup_kind: cleanup_kind,
        image_not_found_message: image_not_found_message
      )
    end

    # Replace an image located by placeholder text in a table cell.
    #
    # Options:
    #   fit: :cover | :contain | :stretch (default: :stretch)
    #   cleanup_placeholder: true | false (default: true)
    def replace_image_by_placeholder_in_table(placeholder, replacement_source, options = {})
      target_cell = find_table_cell_by_placeholder(placeholder)
      raise Errors::ImagePlaceholderNotFound, "Placeholder not found in table cells: #{placeholder}" if target_cell.nil?

      replace_image_within_host(
        target_cell,
        placeholder,
        replacement_source,
        options,
        cleanup_kind: :cell,
        image_not_found_message: "No image found in the same cell as placeholder: #{placeholder}"
      )
    end

    # Batch replacement for a single placeholder anchored in table cell.
    #
    # +placeholder+ identifies the template cell and row. Images are placed into that
    # same cell, up to +max_images_per_row+ per row. If images exceed one row, the
    # template row is duplicated and appended.
    #
    # Returns an array of placement hashes:
    #   [{ row_index: 0, slot_index: 0, relationship_id: "rId25", entry_path: "word/media/image_generated_1.png" }, ...]
    def replace_images_by_placeholder_in_table(placeholder, replacement_sources = [], options = {})
      replacement_sources = Array(replacement_sources).compact

      cleanup_placeholder = options.fetch(:cleanup_placeholder, true)

      template_cell = find_table_cell_by_placeholder(placeholder)

      if replacement_sources.empty?
        cleanup_empty_placeholder_in_table(template_cell, placeholder) if template_cell && cleanup_placeholder
        return []
      end

      raise Errors::ImagePlaceholderNotFound, "Placeholder not found in table cells: #{placeholder}" if template_cell.nil?

      embed_attr = template_cell.at_xpath('.//a:blip/@r:embed', XML_NAMESPACES)
      raise Errors::ImageNotFound, "No placeholder image found in the same cell as placeholder: #{placeholder}" if embed_attr.nil?

      fit = normalize_fit_option(options.fetch(:fit, :stretch))
      width_cm = options[:width]
      height_cm = options[:height]
      max_images_per_row = options.fetch(:max_images_per_row, 2).to_i
      raise ArgumentError, 'max_images_per_row must be >= 1' if max_images_per_row < 1

      template_row = template_cell.at_xpath('./ancestor::w:tr[1]', XML_NAMESPACES)
      raise Errors::ImageNotFound, "No template row found for placeholder: #{placeholder}" if template_row.nil?
      row_template = template_row.dup(1)

      row_nodes = [template_row]
      placements = []
      cell_index = table_cell_index_within_row(template_row, template_cell)

      replacement_sources.each_with_index do |replacement_source, index|
        row_index = index / max_images_per_row
        slot_index = index % max_images_per_row

        if row_index >= row_nodes.length
          cloned = row_template.dup(1)
          row_nodes.last.add_next_sibling(cloned)
          row_nodes << cloned
        end

        current_row = row_nodes[row_index]
        current_cell = current_row.xpath('./w:tc', XML_NAMESPACES)[cell_index]
        raise Errors::ImageNotFound, "Row #{row_index + 1} does not contain target cell index #{cell_index}" if current_cell.nil?

        slot = ensure_image_slot_in_cell(current_cell, slot_index)
        raise Errors::ImageNotFound, "Unable to create image slot #{slot_index + 1} for row #{row_index + 1}" if slot.nil?

        replacement_contents = read_replacement_source(replacement_source)
        generated = create_media_binding_for_slot(slot[:embed_attr], replacement_contents)
        apply_image_size_to_drawing(slot[:drawing_node], width_cm, height_cm, replacement_contents)
        apply_image_fit_to_drawing(slot[:drawing_node], fit, replacement_contents) if fit != :stretch

        placements << {
          row_index: row_index,
          slot_index: slot_index,
          relationship_id: generated[:relationship_id],
          entry_path: generated[:entry_path],
          fit: fit
        }
      end

      remove_placeholder_from_row_nodes(row_nodes, placeholder) if cleanup_placeholder
      placements
    end

    # Insert an image at a placeholder text in any paragraph (body or table cell).
    #
    # Options:
    #   fit: :cover | :contain | :stretch (default: :contain)
    #   width: width in cm
    #   height: height in cm
    #   cleanup_placeholder: true | false (default: true)
    def insert_image_at_placeholder(placeholder, source, options = {})
      insert_images_at_placeholder(placeholder, [source], options).first
    end

    # Insert multiple images at a placeholder text in the same paragraph.
    #
    # Returns an array of placement hashes:
    #   [{ relationship_id: "rId2", entry_path: "word/media/image_generated_1.png", fit: :contain }, ...]
    def insert_images_at_placeholder(placeholder, sources = [], options = {})
      sources = Array(sources).compact
      fit = normalize_fit_option(options.fetch(:fit, :contain))
      cleanup_placeholder = options.fetch(:cleanup_placeholder, true)
      width_cm = options[:width]
      height_cm = options[:height]

      paragraph = find_paragraph_by_placeholder(placeholder)

      if sources.empty?
        remove_placeholder_from_paragraph(paragraph, placeholder) if paragraph && cleanup_placeholder
        return []
      end

      raise Errors::ImagePlaceholderNotFound, "Placeholder not found: #{placeholder}" if paragraph.nil?

      anchor_run = find_run_with_placeholder(paragraph, placeholder)
      last_inserted = anchor_run
      placements = []

      sources.each do |source|
        image_bytes = read_replacement_source(source)
        placement = insert_drawing_at_paragraph(
          paragraph,
          image_bytes,
          fit: fit,
          width_cm: width_cm,
          height_cm: height_cm,
          insert_after: last_inserted
        )
        last_inserted = placement.delete(:run_node)
        placements << placement
      end

      remove_placeholder_from_paragraph(paragraph, placeholder) if cleanup_placeholder
      placements
    end

    # Toggle a character-based checkbox glyph within the paragraph containing +locator+.
    #
    #   set_checkbox('选项A', checked: true)
    #   set_checkbox('[ ]', checked: true, unchecked_glyph: '[ ]', checked_glyph: '[x]')
    def set_checkbox(locator, checked: true, checked_glyph: "\u2611", unchecked_glyph: "\u2610")
      paragraph = find_paragraph_by_placeholder(locator)
      raise Errors::ImagePlaceholderNotFound, "Checkbox locator not found: #{locator}" if paragraph.nil?

      from_glyph = checked ? unchecked_glyph : checked_glyph
      to_glyph = checked ? checked_glyph : unchecked_glyph

      paragraph.xpath('.//w:t', XML_NAMESPACES).each do |text_node|
        text_node.content = text_node.content.gsub(from_glyph, to_glyph)
      end

      true
    end

    # Set a Word content-control checkbox (w:sdt + w14:checkbox) by tag or alias.
    #
    #   check_content_control('opt_a', checked: true)
    def check_content_control(tag_or_alias, checked: true)
      namespaces = xml_namespaces_with_w14
      sdt = find_content_control_checkbox(tag_or_alias, namespaces)
      raise Errors::ImagePlaceholderNotFound, "Content control checkbox not found: #{tag_or_alias}" if sdt.nil?

      checkbox = sdt.at_xpath('.//w14:checkbox', namespaces)
      set_content_control_checked_state(checkbox, checked, namespaces)
      sync_content_control_checkbox_glyph(sdt, checkbox, checked, namespaces)

      true
    end

    def default_paragraph_style
      @styles.at_xpath("w:styles/w:style[@w:type='paragraph' and @w:default='1']/w:name/@w:val").value
    end

    def style_name_of(style_id)
      styles_configuration.style_of(style_id).name
    end

    def styles_configuration
      @styles_configuration ||= Elements::Containers::StylesConfiguration.new(@styles)
    end

    def add_part(zip_path, content_type, bytes)
      replace_entry(zip_path, bytes)
      register_content_type_override(zip_path, content_type) if content_type
      zip_path
    end

    def add_relationship(type, target, mode: nil, id: nil)
      relationship_id = id || next_relationship_id
      relationships_node = @rels.at_xpath('/xmlns:Relationships')
      relation = Nokogiri::XML::Node.new('Relationship', @rels)
      relation['Id'] = relationship_id
      relation['Type'] = type
      relation['Target'] = target
      relation['TargetMode'] = 'External' if mode == :external
      relationships_node.add_child(relation)
      relationship_id
    end

    def ensure_default_content_type(ext, content_type)
      xml = @replace[CONTENT_TYPES_PATH]
      return unless xml

      ext = ext.to_s.downcase
      content_types = Nokogiri::XML(xml)
      types_node = content_types.at_xpath('/xmlns:Types', 'xmlns' => CONTENT_TYPES_NS)
      return unless types_node

      existing = types_node.xpath("xmlns:Default[@Extension='#{ext}']", 'xmlns' => CONTENT_TYPES_NS)
      return unless existing.empty?

      default_node = Nokogiri::XML::Node.new('Default', content_types)
      default_node['Extension'] = ext
      default_node['ContentType'] = content_type
      types_node.add_child(default_node)
      @replace[CONTENT_TYPES_PATH] = content_types.serialize(save_with: 0)
    end

    def ensure_numbering!
      if @numbering.nil?
        @numbering = Nokogiri::XML(
          '<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"></w:numbering>'
        )
        add_part('word/numbering.xml', NUMBERING_CONTENT_TYPE, @numbering.serialize(save_with: 0))
        add_relationship(NUMBERING_REL_TYPE, 'numbering.xml')
      end
      @numbering
    end

    # Import a body node from +source_doc+ with style/numbering isolation.
    # Returns a node in this document's context, ready to insert.
    def import_node(source_doc, node, importer: nil, fallback: true)
      importer ||= (@merge_importers ||= {})[source_doc] ||= Merge::Importer.new(self, source_doc)
      importer.import(node)
    rescue StandardError => e
      raise unless fallback

      warn("Docx::Document#import_node failed: #{e.message}")
      node.dup(1)
    end

    # Import a node from +source_doc+ and insert it before +anchor_node+.
    def import_before(source_doc, node, anchor_node)
      imported = import_node(source_doc, node)
      anchor_node.add_previous_sibling(imported)
      imported
    end

    # Import a node from +source_doc+ and insert it after +anchor_node+.
    def import_after(source_doc, node, anchor_node)
      imported = import_node(source_doc, node)
      anchor_node.add_next_sibling(imported)
      imported
    end

    private

    def with_strict_rescue(strict)
      yield
    rescue Errors::ImagePlaceholderNotFound
      raise if strict
    end

    def render_table_rows(table_spec, multiline:, strict:)
      placeholder_row = table_spec[:placeholder_row] || table_spec['placeholder_row']
      rows = table_spec[:rows] || table_spec['rows']
      return if rows.nil? || rows.empty?

      template_tr = @doc.xpath('//w:tr', XML_NAMESPACES).find do |tr|
        tr.xpath('.//w:t', XML_NAMESPACES).map(&:text).join.include?(placeholder_row)
      end

      if template_tr.nil?
        raise Errors::ImagePlaceholderNotFound, "Template row not found: #{placeholder_row}" if strict

        return
      end

      last_inserted = template_tr
      rows.each do |row_data|
        cloned = template_tr.dup(1)
        cloned.xpath('.//w:p', XML_NAMESPACES).each do |p_node|
          paragraph = Elements::Containers::Paragraph.new(p_node, document_properties, self)
          row_data.each do |ph, val|
            paragraph.substitute(ph, val.to_s, multiline: multiline)
          end
          paragraph.substitute(placeholder_row, '', multiline: false)
        end
        last_inserted.add_next_sibling(cloned)
        last_inserted = cloned
      end

      template_tr.remove
    end

    def render_image(placeholder, source, image_options:, strict:)
      with_strict_rescue(strict) do
        if source.is_a?(Array)
          render_image_array(placeholder, source, image_options)
        else
          render_single_image(placeholder, source, image_options)
        end
      end
    end

    def render_single_image(placeholder, source, image_options)
      if placeholder_host_has_image?(placeholder)
        replace_image_by_placeholder(placeholder, source, image_options)
      else
        insert_image_at_placeholder(placeholder, source, image_options)
      end
    end

    def render_image_array(placeholder, sources, image_options)
      sources = Array(sources).compact
      return if sources.empty?

      if placeholder_host_has_image?(placeholder)
        host = placeholder_image_host(placeholder)
        if host&.name == 'tc'
          replace_images_by_placeholder_in_table(placeholder, sources, image_options)
        else
          replace_image_by_placeholder(placeholder, sources.first, image_options)
        end
      else
        insert_images_at_placeholder(placeholder, sources, image_options)
      end
    end

    def placeholder_image_host(placeholder)
      paragraph = find_paragraph_by_placeholder(placeholder)
      return nil if paragraph.nil?

      paragraph.at_xpath('./ancestor::w:tc[1]', XML_NAMESPACES) || paragraph
    end

    def placeholder_host_has_image?(placeholder)
      host = placeholder_image_host(placeholder)
      return false if host.nil?

      !host.at_xpath('.//a:blip', XML_NAMESPACES).nil?
    end

    def extract_documents
      DOCUMENT_PATHS.each do |attr_name, path|
        if path.match /\*/
          extract_multiple_documents_from_globbed_path(attr_name, path)
        else
          extract_single_document_from_path(attr_name, path)
        end
      end
    end

    def extract_single_document_from_path(attr_name, path)
      if @zip.find_entry(path)
        xml_doc = @zip.read(path)
        self.instance_variable_set(:"@#{attr_name}", Nokogiri::XML(xml_doc))
      end
    end

    def extract_multiple_documents_from_globbed_path(hash_attr_name, glob_path)
      files = @zip.glob(glob_path).map { |h| h.name }
      filename_and_contents_pairs = files.map do |file|
        simple_file_name = file.sub(/^word\//, "").sub(/\.xml$/, "")
        [simple_file_name, Nokogiri::XML(@zip.read(file))]
      end 
      hash = Hash[filename_and_contents_pairs]
      self.instance_variable_set(:"@#{hash_attr_name}", hash)
    end

    def load_styles
      @styles = Nokogiri::XML(@zip.read('word/styles.xml'))
      load_rels
    rescue Errno::ENOENT => e
      warn e.message
      nil
    end

    def load_rels
      rels_entry = @zip.glob('word/_rels/document*.xml.rels').first
      raise Errno::ENOENT unless rels_entry

      @rels_path = rels_entry.name
      @rels = Nokogiri::XML(rels_entry.get_input_stream.read)
      load_content_types
    end

    def load_content_types
      entry = @zip.find_entry(CONTENT_TYPES_PATH)
      return unless entry

      @replace[CONTENT_TYPES_PATH] = entry.get_input_stream.read
    rescue Errno::ENOENT
      nil
    end

    #--
    # TODO: Flesh this out to be compatible with other files
    # TODO: Method to set flag on files that have been edited, probably by inserting something at the
    # end of methods that make edits?
    #++
    def update
      replace_entry 'word/document.xml', doc.serialize(save_with: 0)
      replace_entry 'word/styles.xml', @styles.serialize(save_with: 0) if @styles
      replace_entry @rels_path, @rels.serialize(save_with: 0) if @rels_path && @rels
      DOCUMENT_PATHS.each do |attr_name, path|
        if path.match /\*/
          self.instance_variable_get("@#{attr_name}").each do |simple_file_name, contents|
            replace_entry("word/#{simple_file_name}.xml", contents.serialize(:save_with => 0))
          end
        else
          xml_document = self.instance_variable_get("@#{attr_name}")
          replace_entry path, xml_document.serialize(:save_with => 0) if xml_document
        end
      end
    end

    # generate Elements::Containers::Paragraph from paragraph XML node
    def parse_paragraph_from(p_node)
      Elements::Containers::Paragraph.new(p_node, document_properties, self)
    end

    # generate Elements::Bookmark from bookmark XML node
    def parse_bookmark_from(b_node)
      Elements::Bookmark.new(b_node)
    end

    def parse_table_from(t_node)
      Elements::Containers::Table.new(t_node)
    end

    def resolve_image_entry_path(image_reference)
      if images.key?(image_reference)
        path = images[image_reference]
      else
        path = normalize_entry_path(image_reference)
      end

      return path if zip.find_entry(path)

      raise Errors::ImageNotFound, "Image entry not found: #{image_reference}"
    end

    def normalize_entry_path(path)
      clean_path = path.to_s.sub(%r{\A/+}, '').sub(%r{\A\./}, '')
      clean_path = "word/#{clean_path.sub(%r{\A\.\./}, '')}" if clean_path.start_with?('../')
      clean_path = "word/#{clean_path}" unless clean_path.start_with?('word/')
      clean_path
    end

    def read_replacement_source(replacement_source)
      if replacement_source.respond_to?(:read)
        replacement_source.read
      elsif replacement_source.is_a?(String) && File.exist?(replacement_source)
        File.binread(replacement_source)
      else
        raise ArgumentError, "replacement_source must be an IO-like object or an existing file path"
      end
    end

    def replace_image_within_host(host_node, placeholder, replacement_source, options, cleanup_kind:, image_not_found_message:)
      fit = normalize_fit_option(options.fetch(:fit, :stretch))
      cleanup_placeholder = options.fetch(:cleanup_placeholder, true)
      width_cm = options[:width]
      height_cm = options[:height]

      embed_attr = host_node.at_xpath('.//a:blip/@r:embed', XML_NAMESPACES)
      raise Errors::ImageNotFound, image_not_found_message if embed_attr.nil?

      rid = embed_attr.value
      image_entry_path = resolve_image_entry_path(rid)
      replacement_contents = read_replacement_source(replacement_source)

      replace_entry(image_entry_path, replacement_contents)

      drawing_node = host_node.at_xpath(".//w:drawing[.//a:blip[@r:embed='#{rid}']]", XML_NAMESPACES)
      if drawing_node
        apply_image_size_to_drawing(drawing_node, width_cm, height_cm, replacement_contents)
        apply_image_fit_to_drawing(drawing_node, fit, replacement_contents) if fit != :stretch
      end

      if cleanup_placeholder
        case cleanup_kind
        when :cell
          remove_placeholder_from_cell(host_node, placeholder)
        when :paragraph
          remove_placeholder_from_paragraph(host_node, placeholder)
        end
      end

      {
        relationship_id: rid,
        entry_path: image_entry_path,
        fit: fit
      }
    end

    def find_table_cell_by_placeholder(placeholder)
      doc.xpath('//w:tbl//w:tr//w:tc', XML_NAMESPACES).find do |cell|
        text = cell.xpath('.//w:t', XML_NAMESPACES).map(&:text).join
        text.include?(placeholder)
      end
    end

    def find_paragraph_by_placeholder(placeholder)
      doc.xpath('//w:p', XML_NAMESPACES).find do |paragraph|
        text = paragraph.xpath('.//w:t', XML_NAMESPACES).map(&:text).join
        text.include?(placeholder)
      end
    end

    W14_NS = 'http://schemas.microsoft.com/office/word/2010/wordml'

    def xml_namespaces_with_w14
      XML_NAMESPACES.merge('w14' => W14_NS)
    end

    def find_content_control_checkbox(tag_or_alias, namespaces)
      doc.xpath('//w:sdt', namespaces).find do |sdt|
        sdt_pr = sdt.at_xpath('./w:sdtPr', namespaces)
        next unless sdt_pr&.at_xpath('.//w14:checkbox', namespaces)

        tag = sdt_pr.at_xpath('./w:tag/@w:val', namespaces)&.value
        alias_val = sdt_pr.at_xpath('./w:alias/@w:val', namespaces)&.value
        [tag, alias_val].include?(tag_or_alias)
      end
    end

    def set_content_control_checked_state(checkbox, checked, namespaces)
      checked_node = checkbox.at_xpath('./w14:checked', namespaces)
      unless checked_node
        ensure_w14_namespace_declared(checkbox)
        checked_node = Nokogiri::XML::Node.new('w14:checked', @doc)
        checkbox.add_child(checked_node)
      end
      checked_node['w14:val'] = checked ? '1' : '0'
    end

    def sync_content_control_checkbox_glyph(sdt, checkbox, checked, namespaces)
      state_xpath = checked ? './w14:checkedState/@w14:val' : './w14:uncheckedState/@w14:val'
      state_val = checkbox.at_xpath(state_xpath, namespaces)&.value
      return unless state_val

      glyph = state_val.to_i(16).chr(Encoding::UTF_8)
      sdt_content = sdt.at_xpath('./w:sdtContent', namespaces)
      return unless sdt_content

      text_node = sdt_content.at_xpath('.//w:t', namespaces)
      if text_node
        text_node.content = glyph
      else
        run = sdt_content.at_xpath('./w:r', namespaces)
        unless run
          run = Nokogiri::XML::Node.new('w:r', @doc)
          sdt_content.add_child(run)
        end
        text_node = Nokogiri::XML::Node.new('w:t', @doc)
        text_node.content = glyph
        run.add_child(text_node)
      end
    end

    def ensure_w14_namespace_declared(node)
      return if @doc.root&.namespaces&.fetch('w14', nil) == W14_NS

      ancestor = node
      while ancestor
        return if ancestor.namespace_definitions.any? { |ns| ns.prefix == 'w14' && ns.href == W14_NS }

        ancestor = ancestor.parent
      end

      node.add_namespace_definition('w14', W14_NS)
    end

    def find_run_with_placeholder(paragraph, placeholder)
      paragraph.xpath('./w:r', XML_NAMESPACES).find do |run|
        text = run.xpath('.//w:t', XML_NAMESPACES).map(&:text).join
        text.include?(placeholder)
      end
    end

    def remove_placeholder_from_paragraph(paragraph, placeholder)
      text_nodes = paragraph.xpath('.//w:t', XML_NAMESPACES)
      return if text_nodes.empty?

      merged_text = text_nodes.map(&:text).join
      return unless merged_text.include?(placeholder)

      text_nodes.first.content = merged_text.gsub(placeholder, '')
      text_nodes.drop(1).each { |node| node.content = '' }
    end

    def table_cell_index_within_row(row_node, cell_node)
      row_node.xpath('./w:tc', XML_NAMESPACES).index(cell_node) || 0
    end

    def ensure_image_slot_in_cell(cell_node, slot_index)
      drawings = cell_node.xpath('.//w:drawing', XML_NAMESPACES).to_a
      while drawings.length <= slot_index
        duplicate_image_slot_in_cell(cell_node)
        drawings = cell_node.xpath('.//w:drawing', XML_NAMESPACES).to_a
      end

      drawing_node = drawings[slot_index]
      return nil unless drawing_node

      embed_attr = drawing_node.at_xpath('.//a:blip/@r:embed', XML_NAMESPACES)
      return nil unless embed_attr

      { cell: cell_node, embed_attr: embed_attr, drawing_node: drawing_node }
    end

    def duplicate_image_slot_in_cell(cell_node)
      template_run = cell_node.at_xpath('.//w:r[w:drawing]', XML_NAMESPACES)
      return nil unless template_run

      target_paragraph = template_run.parent
      target_paragraph.add_child(template_run.dup(1))
    end

    def remove_placeholder_from_cell(cell, placeholder)
      cell.xpath('.//w:p', XML_NAMESPACES).each do |paragraph|
        text_nodes = paragraph.xpath('.//w:t', XML_NAMESPACES)
        next if text_nodes.empty?

        merged_text = text_nodes.map(&:text).join
        next unless merged_text.include?(placeholder)

        text_nodes.first.content = merged_text.gsub(placeholder, '')
        text_nodes.drop(1).each { |node| node.content = '' }
      end
    end

    def remove_placeholder_from_row_nodes(row_nodes, placeholder)
      row_nodes.each do |row|
        row.xpath('.//w:p', XML_NAMESPACES).each do |paragraph|
          text_nodes = paragraph.xpath('.//w:t', XML_NAMESPACES)
          next if text_nodes.empty?

          merged_text = text_nodes.map(&:text).join
          next unless merged_text.include?(placeholder)

          text_nodes.first.content = merged_text.gsub(placeholder, '')
          text_nodes.drop(1).each { |node| node.content = '' }
        end
      end
    end

    def cleanup_empty_placeholder_in_table(cell_node, placeholder)
      remove_placeholder_from_cell(cell_node, placeholder)
      cell_node.xpath('.//w:drawing', XML_NAMESPACES).each(&:remove)
    end

    def normalize_fit_option(fit)
      fit_value = fit.to_sym
      return fit_value if IMAGE_FIT_MODES.include?(fit_value)

      raise ArgumentError, "fit must be one of: #{IMAGE_FIT_MODES.join(', ')}"
    end

    def apply_image_size_to_drawing(drawing_node, width_cm, height_cm, replacement_contents)
      return unless width_cm || height_cm

      wp_extent = drawing_node.at_xpath('.//wp:extent', XML_NAMESPACES)
      xfrm_extent = drawing_node.at_xpath('.//pic:spPr/a:xfrm/a:ext', XML_NAMESPACES)
      return unless wp_extent && xfrm_extent

      source_width, source_height = image_size_from_bytes(replacement_contents)
      source_ratio = source_width.to_f / source_height

      if width_cm && height_cm
        target_cx = (width_cm * CM_TO_EMU).round
        target_cy = (height_cm * CM_TO_EMU).round
      elsif width_cm
        target_cx = (width_cm * CM_TO_EMU).round
        target_cy = (target_cx / source_ratio).round
      else
        target_cy = (height_cm * CM_TO_EMU).round
        target_cx = (target_cy * source_ratio).round
      end

      wp_extent['cx'] = target_cx.to_s
      wp_extent['cy'] = target_cy.to_s
      xfrm_extent['cx'] = target_cx.to_s
      xfrm_extent['cy'] = target_cy.to_s
    end

    def apply_image_fit_to_drawing(drawing_node, fit, replacement_contents)
      source_width, source_height = image_size_from_bytes(replacement_contents)
      if fit == :cover
        apply_cover_fit(drawing_node, source_width, source_height)
      elsif fit == :contain
        apply_contain_fit(drawing_node, source_width, source_height)
      end
    end

    def image_size_from_bytes(bytes)
      return png_size_from_bytes(bytes) if bytes.start_with?("\x89PNG\r\n\x1A\n".b)
      return jpeg_size_from_bytes(bytes) if bytes.start_with?("\xFF\xD8".b)

      raise ArgumentError, "Unsupported image format. Only PNG and JPEG are supported for fit modes."
    end

    def png_size_from_bytes(bytes)
      [bytes[16, 4].unpack1('N'), bytes[20, 4].unpack1('N')]
    end

    def jpeg_size_from_bytes(bytes)
      io = StringIO.new(bytes)
      io.read(2) # SOI
      until io.eof?
        marker_prefix = io.read(1)&.ord
        next unless marker_prefix == 0xFF

        marker = io.read(1)&.ord
        next if marker.nil? || marker == 0xD8 || marker == 0xD9
        next if marker == 0x01 || (0xD0..0xD7).include?(marker)

        length = io.read(2)&.unpack1('n')
        break unless length && length >= 2

        if [0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF].include?(marker)
          io.read(1) # precision
          height = io.read(2).unpack1('n')
          width = io.read(2).unpack1('n')
          return [width, height]
        end

        io.read(length - 2)
      end

      raise ArgumentError, "Cannot parse JPEG size: invalid image"
    end

    def apply_cover_fit(drawing_node, source_width, source_height)
      extent = drawing_node.at_xpath('.//wp:extent', XML_NAMESPACES)
      return unless extent

      target_width = extent['cx'].to_f
      target_height = extent['cy'].to_f
      return if target_width <= 0 || target_height <= 0

      source_ratio = source_width.to_f / source_height
      target_ratio = target_width / target_height

      blip_fill = drawing_node.at_xpath('.//pic:blipFill', XML_NAMESPACES)
      return unless blip_fill

      if source_ratio > target_ratio
        visible_width_ratio = target_ratio / source_ratio
        crop_percent = ((1.0 - visible_width_ratio) / 2.0 * 100_000).round
        set_or_create_src_rect(blip_fill, 'l' => crop_percent, 'r' => crop_percent, 't' => 0, 'b' => 0)
      else
        visible_height_ratio = source_ratio / target_ratio
        crop_percent = ((1.0 - visible_height_ratio) / 2.0 * 100_000).round
        set_or_create_src_rect(blip_fill, 'l' => 0, 'r' => 0, 't' => crop_percent, 'b' => crop_percent)
      end
    end

    def apply_contain_fit(drawing_node, source_width, source_height)
      wp_extent = drawing_node.at_xpath('.//wp:extent', XML_NAMESPACES)
      xfrm_extent = drawing_node.at_xpath('.//pic:spPr/a:xfrm/a:ext', XML_NAMESPACES)
      return unless wp_extent && xfrm_extent

      frame_width = wp_extent['cx'].to_f
      frame_height = wp_extent['cy'].to_f
      return if frame_width <= 0 || frame_height <= 0

      source_ratio = source_width.to_f / source_height
      frame_ratio = frame_width / frame_height

      if source_ratio > frame_ratio
        new_width = frame_width
        new_height = (frame_width / source_ratio).round
      else
        new_height = frame_height
        new_width = (frame_height * source_ratio).round
      end

      wp_extent['cx'] = new_width.to_i.to_s
      wp_extent['cy'] = new_height.to_i.to_s
      xfrm_extent['cx'] = new_width.to_i.to_s
      xfrm_extent['cy'] = new_height.to_i.to_s

      blip_fill = drawing_node.at_xpath('.//pic:blipFill', XML_NAMESPACES)
      remove_src_rect(blip_fill) if blip_fill
    end

    def set_or_create_src_rect(blip_fill_node, attrs)
      src_rect = blip_fill_node.at_xpath('./a:srcRect', XML_NAMESPACES)
      unless src_rect
        src_rect = Nokogiri::XML::Node.new('a:srcRect', blip_fill_node.document)
        blip = blip_fill_node.at_xpath('./a:blip', XML_NAMESPACES)
        if blip
          blip.add_next_sibling(src_rect)
        else
          blip_fill_node.prepend_child(src_rect)
        end
      end
      attrs.each { |key, value| src_rect[key] = value.to_i.to_s }
    end

    def remove_src_rect(blip_fill_node)
      src_rect = blip_fill_node.at_xpath('./a:srcRect', XML_NAMESPACES)
      src_rect.remove if src_rect
    end

    def create_media_binding_for_slot(embed_attr, replacement_contents)
      ext = extension_for_image_bytes(replacement_contents)
      entry_path = next_generated_media_path(ext)
      relationship_id = next_relationship_id

      add_image_relationship(relationship_id, entry_path)
      replace_entry(entry_path, replacement_contents)
      ensure_content_type_default(ext)
      embed_attr.value = relationship_id

      { relationship_id: relationship_id, entry_path: entry_path }
    end

    def ensure_content_type_default(ext)
      ext = ext.to_s.downcase
      content_type = CONTENT_TYPE_MAPPINGS[ext]
      return unless content_type

      ensure_default_content_type(ext, content_type)
    end

    def register_content_type_override(zip_path, content_type)
      xml = @replace[CONTENT_TYPES_PATH]
      return unless xml

      content_types = Nokogiri::XML(xml)
      types_node = content_types.at_xpath('/xmlns:Types', 'xmlns' => CONTENT_TYPES_NS)
      return unless types_node

      part_name = "/#{zip_path}"
      existing = types_node.xpath("xmlns:Override[@PartName='#{part_name}']", 'xmlns' => CONTENT_TYPES_NS)
      return unless existing.empty?

      override_node = Nokogiri::XML::Node.new('Override', content_types)
      override_node['PartName'] = part_name
      override_node['ContentType'] = content_type
      types_node.add_child(override_node)
      @replace[CONTENT_TYPES_PATH] = content_types.serialize(save_with: 0)
    end

    def insert_drawing_at_paragraph(paragraph, image_bytes, fit:, width_cm:, height_cm:, insert_after:)
      ext = extension_for_image_bytes(image_bytes)
      entry_path = next_generated_media_path(ext)
      relationship_id = next_relationship_id

      add_image_relationship(relationship_id, entry_path)
      replace_entry(entry_path, image_bytes)
      ensure_content_type_default(ext)

      cx, cy = initial_extent_emus(width_cm, height_cm, image_bytes)
      docpr_id = next_docpr_id
      name = "Image #{docpr_id}"
      run_node = build_drawing_run_node(relationship_id, cx, cy, docpr_id, name)

      if insert_after
        insert_after.add_next_sibling(run_node)
      else
        paragraph.add_child(run_node)
      end

      drawing_node = run_node.at_xpath('./w:drawing', XML_NAMESPACES)
      apply_image_size_to_drawing(drawing_node, width_cm, height_cm, image_bytes) if width_cm || height_cm
      apply_image_fit_to_drawing(drawing_node, fit, image_bytes) if fit != :stretch && width_cm && height_cm

      {
        relationship_id: relationship_id,
        entry_path: entry_path,
        fit: fit,
        run_node: run_node
      }
    end

    def initial_extent_emus(width_cm, height_cm, image_bytes)
      if width_cm || height_cm
        source_width, source_height = image_size_from_bytes(image_bytes)
        source_ratio = source_width.to_f / source_height

        if width_cm && height_cm
          [(width_cm * CM_TO_EMU).round, (height_cm * CM_TO_EMU).round]
        elsif width_cm
          cx = (width_cm * CM_TO_EMU).round
          [cx, (cx / source_ratio).round]
        else
          cy = (height_cm * CM_TO_EMU).round
          [(cy * source_ratio).round, cy]
        end
      else
        compute_default_image_emus(image_bytes)
      end
    end

    def compute_default_image_emus(image_bytes)
      source_width, source_height = image_size_from_bytes(image_bytes)
      cx = (source_width / 96.0 * 914_400).round
      cy = (source_height / 96.0 * 914_400).round

      if cx > MAX_IMAGE_WIDTH_EMU
        ratio = MAX_IMAGE_WIDTH_EMU.to_f / cx
        cx = MAX_IMAGE_WIDTH_EMU
        cy = (cy * ratio).round
      end

      [cx, cy]
    end

    def next_docpr_id
      max_id = doc.xpath('//wp:docPr/@id', XML_NAMESPACES).map { |attr| attr.value.to_i }.max || 0
      max_id + 1
    end

    def build_drawing_run_node(rid, cx, cy, docpr_id, name)
      xml = <<~XML
        <w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
          <w:drawing>
            <wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" distT="0" distB="0" distL="0" distR="0">
              <wp:extent cx="#{cx}" cy="#{cy}"/>
              <wp:effectExtent l="0" t="0" r="0" b="0"/>
              <wp:docPr id="#{docpr_id}" name="#{name}"/>
              <wp:cNvGraphicFramePr>
                <a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/>
              </wp:cNvGraphicFramePr>
              <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
                <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
                  <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
                    <pic:nvPicPr>
                      <pic:cNvPr id="#{docpr_id}" name="#{name}"/>
                      <pic:cNvPicPr/>
                    </pic:nvPicPr>
                    <pic:blipFill>
                      <a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="#{rid}"/>
                      <a:stretch><a:fillRect/></a:stretch>
                    </pic:blipFill>
                    <pic:spPr>
                      <a:xfrm><a:off x="0" y="0"/><a:ext cx="#{cx}" cy="#{cy}"/></a:xfrm>
                      <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
                    </pic:spPr>
                  </pic:pic>
                </a:graphicData>
              </a:graphic>
            </wp:inline>
          </w:drawing>
        </w:r>
      XML

      fragment = Nokogiri::XML::DocumentFragment.parse(xml)
      fragment.at_xpath('./w:r', XML_NAMESPACES)
    end

    def extension_for_image_bytes(bytes)
      return 'png' if bytes.start_with?("\x89PNG\r\n\x1A\n".b)
      return 'jpg' if bytes.start_with?("\xFF\xD8".b)

      raise ArgumentError, 'Unsupported image format. Only PNG and JPEG are supported.'
    end

    def next_generated_media_path(ext)
      existing = zip.glob("word/media/*").map(&:name) + @replace.keys
      max_index = existing.filter_map do |name|
        match = name.match(%r{\Aword/media/image_generated_(\d+)\.(png|jpg)\z})
        match && match[1].to_i
      end.max || 0
      "word/media/image_generated_#{max_index + 1}.#{ext}"
    end

    def next_relationship_id
      max_id = @rels.xpath('//xmlns:Relationship/@Id').filter_map do |attr|
        match = attr.value.match(/\ArId(\d+)\z/)
        match && match[1].to_i
      end.max || 0
      "rId#{max_id + 1}"
    end

    def add_image_relationship(relationship_id, entry_path)
      add_relationship(
        'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image',
        entry_path.sub(%r{\Aword/}, ''),
        id: relationship_id
      )
    end
  end
end